 const amenities = [
    { id: 1, name: 'Bar', value: 'bar' },
    { id: 2, name: 'BBQ', value: 'bbq' },
    { id: 3, name: 'Biergarten', value: 'biergarten' },
    { id: 4, name: 'Cafe', value: 'cafe' },
    { id: 5, name: 'Drinking Water', value: 'drinking_water' },
    { id: 6, name: 'Fast Food', value: 'fast_food' },
    { id: 7, name: 'Food Court', value: 'food_court' },
    { id: 8, name: 'Ice Cream', value: 'ice_cream' },
    { id: 9, name: 'Pub', value: 'pub' },
    { id: 10, name: 'Restaurant', value: 'restaurant' },
    { id: 11, name: 'College', value: 'college' },
    { id: 12, name: 'Kindergarten', value: 'kindergarten' },
    { id: 13, name: 'Library', value: 'library' },
    { id: 14, name: 'School', value: 'school' },
    { id: 15, name: 'University', value: 'university' },
    { id: 16, name: 'Bicycle Parking', value: 'bicycle_parking' },
    { id: 17, name: 'Bicycle Rental', value: 'bicycle_rental' },
    { id: 18, name: 'Bus Station', value: 'bus_station' },
    { id: 19, name: 'Car Rental', value: 'car_rental' },
    { id: 20, name: 'Car Sharing', value: 'car_sharing' },
    { id: 21, name: 'Car Wash', value: 'car_wash' },
    { id: 22, name: 'Charging Station', value: 'charging_station' },
    { id: 23, name: 'Ferry Terminal', value: 'ferry_terminal' },
    { id: 24, name: 'Fuel', value: 'fuel' },
    { id: 25, name: 'Grit Bin', value: 'grit_bin' },
    { id: 26, name: 'Motorcycle Parking', value: 'motorcycle_parking' },
    { id: 27, name: 'Parking', value: 'parking' },
    { id: 28, name: 'Taxi', value: 'taxi' },
    { id: 29, name: 'ATM', value: 'atm' },
    { id: 30, name: 'Bank', value: 'bank' },
    { id: 31, name: 'Bureau de Change', value: 'bureau_de_change' },
    { id: 32, name: 'Baby Hatch', value: 'baby_hatch' },
    { id: 33, name: 'Clinic', value: 'clinic' },
    { id: 34, name: 'Dentist', value: 'dentist' },
    { id: 35, name: 'Doctors', value: 'doctors' },
    { id: 36, name: 'Hospital', value: 'hospital' },
    { id: 37, name: 'Nursing Home', value: 'nursing_home' },
    { id: 38, name: 'Pharmacy', value: 'pharmacy' },
    { id: 39, name: 'Social Facility', value: 'social_facility' },
    { id: 40, name: 'Veterinary', value: 'veterinary' },
    { id: 41, name: 'Arts Centre', value: 'arts_centre' },
    { id: 42, name: 'Brothel', value: 'brothel' },
    { id: 43, name: 'Casino', value: 'casino' },
    { id: 44, name: 'Cinema', value: 'cinema' },
    { id: 45, name: 'Community Centre', value: 'community_centre' },
    { id: 46, name: 'Fountain', value: 'fountain' },
    { id: 47, name: 'Nightclub', value: 'nightclub' },
    { id: 48, name: 'Planetarium', value: 'planetarium' },
    { id: 49, name: 'Theatre', value: 'theatre' },
    { id: 50, name: 'Bicycle Repair Station', value: 'bicycle_repair_station' },
    { id: 51, name: 'Boat Rental', value: 'boat_rental' },
    { id: 52, name: 'Boat Storage', value: 'boat_storage' },
    { id: 53, name: 'Car Repair', value: 'car_repair' },
    { id: 54, name: 'Car Sharing', value: 'car_sharing' },
    { id: 55, name: 'Car Wash', value: 'car_wash' },
    { id: 56, name: 'Electric Vehicle Charging Station', value: 'electric_vehicle_charging_station' },
    { id: 57, name: 'EV Charging', value: 'ev_charging' },
    { id: 58, name: 'Motorcycle Repair', value: 'motorcycle_repair' },
    { id: 59, name: 'Recycling', value: 'recycling' },
    { id: 60, name: 'Waste Basket', value: 'waste_basket' },
    // ... add more amenities as needed
  ];

  export default amenities